name: fastbuy
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # iOS style icons
  cupertino_icons: ^1.0.6

  # State management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Firebase
  firebase_core: ^3.2.0
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.3
  firebase_messaging: ^15.1.3

  # Networking & serialization
  http: ^1.2.1
  freezed_annotation: ^2.4.2
  json_annotation: ^4.9.0

  # Local storage & utilities
  shared_preferences: ^2.2.3
  path_provider: ^2.1.4
  connectivity_plus: ^6.0.4

  # UI & UX
  google_fonts: ^6.2.1
  glassmorphism: ^3.0.0
  fluttertoast: ^8.2.6
  hexcolor: ^3.0.1

  # Localization (CORRECT setup)
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2


  # Media & files
  image_picker: ^1.1.2
  file_picker: ^8.0.7
  image: ^4.5.3

  # Notifications & calls
  flutter_local_notifications: ^17.2.4

  # Auth & APIs
  googleapis_auth: ^1.6.0
  phone_number_picker: ^0.0.8

  # Location
  geolocator: ^13.0.2
  geocoding: ^3.0.0

  # External actions
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  change_app_package_name: ^1.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/lang/en.json
    - assets/lang/es.json

  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/ProximaNovaBold.ttf

    - family: semibold
      fonts:
        - asset: assets/fonts/ProximaNovaBold.ttf

    - family: medium
      fonts:
        - asset: assets/fonts/ProximaNovaRegular.ttf

    - family: regular
      fonts:
        - asset: assets/fonts/ProximaNovaThin.ttf
