# JVM memory
org.gradle.jvmargs=-Xmx4G -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# ? Force Gradle to use Android Studio JDK (VERY IMPORTANT)
org.gradle.java.home=/home/zeocodes/Downloads/android-studio/jbr

# ? Kotlin 2.1 stability flags
kotlin.incremental=true
kotlin.compiler.execution.strategy=in-process

# ? Prevent old Java 8 bytecode assumptions
android.defaults.buildfeatures.buildconfig=true
